### ISSUE TITLE
Memory Leak while training

### ISSUE THREAD

**Issue by hrichiksite** [kinggongzilla/ai-clone-whatsapp#7]
After doing all other steps, when the training starts, it uses up all memory with no progress.

I have tested with up to 210 GB of RAM and it has used it all up and then was killed by the system for OOM error.

The training dataset is 22 MB big.

**Comment by blopa** [comment]
Same here

**Comment by kinggongzilla** [comment]
Hi!

I completely rewrote the project with the new torchtune framework from PyTorch.
I also added Llama3 support and the code should be *much* simpler now.

So I think your issues should hopefully be resolved. Please clone this repo again and follow the new instructions.

Let me know if you still encounter any issues.

**Comment by blopa** [comment]
Hey, nice, thanks. I'm trying to run it on Google Colab in the terminal, but I'm getting an error with the `tune` command:

```
tune run lora_finetune_single_device --config /content/drive/MyDrive/ai-clone-whatsapp/config/mistral/qlora_train_config.yaml

enable_activation_checkpointing: false
epochs: 1
gradient_accumulation_steps: 1
log_every_n_steps: 1
log_peak_memory_stats: false
loss:
  _component_: torch.nn.CrossEntropyLoss
lr_scheduler:
  _component_: torchtune.modules.get_cosine_schedule_with_warmup
  num_warmup_steps: 100
max_steps_per_epoch: null
metric_logger:
  _component_: torchtune.utils.metric_logging.DiskLogger
  log_dir: /tmp/lora_finetune_output
model:
  _component_: torchtune.models.mistral.qlora_mistral_7b
  apply_lora_to_mlp: false
  apply_lora_to_output: false
  lora_alpha: 32
  lora_attn_modules:
  - q_proj
  - v_proj
  lora_rank: 8
optimizer:
  _component_: torch.optim.AdamW
  lr: 0.0001
output_dir: /tmp/lora_finetune_output
profiler:
  _component_: torchtune.utils.profiler
  enabled: false
resume_from_checkpoint: false
seed: 42
shuffle: true
tokenizer:
  _component_: torchtune.models.mistral.mistral_tokenizer
  path: /content/drive/MyDrive/ai-clone-whatsapp/model/mistral/original/tokenizer.model

DEBUG:torchtune.utils.logging:Setting manual seed to local seed 42. Local seed is seed + rank = 42 + 0
Writing logs to /tmp/lora_finetune_output/log_1714341655.txt
Traceback (most recent call last):
  File "/usr/local/bin/tune", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/torchtune/_cli/tune.py", line 49, in main
    parser.run(args)
  File "/usr/local/lib/python3.10/dist-packages/torchtune/_cli/tune.py", line 43, in run
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/torchtune/_cli/run.py", line 179, in _run_cmd
    self._run_single_device(args)
  File "/usr/local/lib/python3.10/dist-packages/torchtune/_cli/run.py", line 93, in _run_single_device
    runpy.run_path(str(args.recipe), run_name="__main__")
  File "/usr/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/recipes/lora_finetune_single_device.py", line 528, in <module>
    sys.exit(recipe_main())
  File "/usr/local/lib/python3.10/dist-packages/torchtune/config/_parse.py", line 50, in wrapper
    sys.exit(recipe_main(conf))
  File "/usr/local/lib/python3.10/dist-packages/recipes/lora_finetune_single_device.py", line 522, in recipe_main
    recipe.setup(cfg=cfg)
  File "/usr/local/lib/python3.10/dist-packages/recipes/lora_finetune_single_device.py", line 183, in setup
    checkpoint_dict = self.load_checkpoint(cfg_checkpointer=cfg.checkpointer)
  File "/usr/local/lib/python3.10/dist-packages/recipes/lora_finetune_single_device.py", line 136, in load_checkpoint
    self._checkpointer = config.instantiate(
  File "/usr/local/lib/python3.10/dist-packages/torchtune/config/_instantiate.py", line 106, in instantiate
    return _instantiate_node(config, *args)
  File "/usr/local/lib/python3.10/dist-packages/torchtune/config/_instantiate.py", line 31, in _instantiate_node
    return _create_component(_component_, args, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torchtune/config/_instantiate.py", line 20, in _create_component
    return _component_(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torchtune/utils/_checkpointing/_checkpointer.py", line 517, in __init__
    self._checkpoint_path = get_path(self._checkpoint_dir, checkpoint_files[0])
  File "/usr/local/lib/python3.10/dist-packages/torchtune/utils/_checkpointing/_checkpointer_utils.py", line 50, in get_path
    raise ValueError(f"No file with name: {filename} found in {input_dir}.")
ValueError: No file with name: consolidated.00.pth found in /content/drive/MyDrive/ai-clone-whatsapp/model/mistral/original.
```

**Comment by kinggongzilla** [comment]
Ah ok. Can you tell me what files you have in the mistral/original directory?

**Comment by blopa** [comment]
I didn't have a `original` directory at all actually. I then got an error saying that, so I created one, with no files inside, and then got this error.

But now I'm running with Llama and it seems to be working. Let's see.

**Comment by kinggongzilla** [comment]
the origin directory gets created when running the download command as described in the readme. 
Great that it worked for you with llama. Let me know how it went
