### ISSUE TITLE
Finetuning command doesn't work

### ISSUE THREAD

**Issue by AntouanK** [kinggongzilla/ai-clone-whatsapp#8]
I prepared the csv, but in the next step I get this:

```
❯ python -m finetuning --dataset "custom_dataset" --custom_dataset.file "scripts/custom_dataset.py" --whatsapp_username "Jorge"
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/antouank/_REPOS_/ai-clone-whatsapp/finetuning.py", line 7, in <module>
    from train import main
  File "/home/antouank/_REPOS_/ai-clone-whatsapp/train.py", line 11, in <module>
    from peft import get_peft_model, prepare_model_for_int8_training
ImportError: cannot import name 'prepare_model_for_int8_training' from 'peft' (/home/antouank/_REPOS_/ai-clone-whatsapp/venv/lib/python3.11/site-packages/peft/__init__.py)
```

**Comment by AntouanK** [comment]
I'm guessing it's connected to this https://github.com/huggingface/peft/issues/1583 ?

**Comment by kinggongzilla** [comment]
I'll have a look and try and update the code

**Comment by kinggongzilla** [comment]
Hm maybe play around with temperature/top-k parameters etc?

I had about 10k total messages for my finetuning and it definitely did pick up on my writing style. I did have to play around a bit with some hyperparameters.

Also note that Mistral 7B (and other small models) aren't particularly good at non-english languages. So if your training data isn't in english, I think finetuning will not work that well. Not sure if this applies to you.

I'll try and update for llama3 over the weekend.

**Comment by AntouanK** [comment]
Good point. Yes, text is in English.

ok, I will try other values. Although I have no idea what I'm tweaking.
Would be interesting if you show a few examples on how to tweak them ( and what they roughly do when you change them ).

The fine-tuning was relatively fast ( about 5-10 mins with my 4090 ). 
Does it matter if I make it run for 2 epochs? If so, how do I do that?

also, I used this csv style :
```csv
0635d995,b9211785,<sender>John Doe</sender>it's so you,12/07/2022,16:41,John Doe
75b8edd5,0635d995,<sender>John Doe</sender>then I'm outta here booooom,12/07/2022,16:42,John Doe
031436be,75b8edd5,<sender>John Doe</sender>you guys arrived?,12/07/2022,16:42,John Doe
ea0de872,031436be,<sender>Antonis</sender>yeah,12/07/2022,16:42,Antonis
c1b410c7,ea0de872,<sender>John Doe</sender>yep 3 minutes and be there,12/07/2022,16:42,John Doe
fd1a3ee9,c1b410c7,<sender>Antonis</sender>ok,12/07/2022,16:44,Antonis
125181dd,fd1a3ee9,<sender>Antonis</sender>there's a queue.,12/07/2022,20:24,Antonis
639d0fb5,125181dd,<sender>Antonis</sender>Hope you are feeling better today!,15/07/2022,09:48,Antonis
476b5305,639d0fb5,<sender>John Doe</sender>nice! have a great one 😀,15/07/2022,10:47,John Doe
844a8521,476b5305,<sender>John Doe</sender>yeah much better now 👏,15/07/2022,10:47,John Doe
26a8fea9,844a8521,<sender>John Doe</sender>thanks,15/07/2022,10:47,John Doe
f5a0ef76,26a8fea9,<sender>John Doe</sender>arrived? nice,15/07/2022,12:01,John Doe
```


Thanks for all your work and support btw :pray:

**Comment by kinggongzilla** [comment]
Hi!

I completely rewrote the project with the new torchtune framework from PyTorch.
I also added Llama3 support.

So I think your issues should hopefully be resolved. Please clone this repo again and follow the new instructions. 

Let me know if you still encounter any issues.

**Comment by AntouanK** [comment]
the regex seems to be wrong for my file ( I'm also in EU btw. Have UK number but mostly lived in EU countries )

![image](https://github.com/kinggongzilla/ai-clone-whatsapp/assets/4569111/32b7e47c-4d5f-4bde-b3d6-610d68409e83)

**Comment by AntouanK** [comment]
I used this pattern:
```
    pattern = r"(\d{2}/\d{2}/\d{4}), (\d{2}:\d{2}) - (.*?):\s*((?:(?!^\d{2}/\d{2}/\d{4}, \d{2}:\d{2})[\s\S])*)"
```

that seemed to make a bunch of json files.

I ran the fine-tuning after.

And tried to chat with the result, but the results are... not conclusive :joy: 

```
❯ tune run chat.py --config config/llama3/inference_config.yaml
INFO:torchtune.utils.logging:Running ChatRecipe with resolved config:

checkpointer:
  _component_: torchtune.utils.FullModelMetaCheckpointer
  checkpoint_dir: model/finetune_checkpoint
  checkpoint_files:
  - meta_model_0.pt
  model_type: LLAMA3
  output_dir: model/finetune_checkpoint
device: cuda
dtype: bf16
max_new_tokens: 4096
model:
  _component_: torchtune.models.llama3.llama3_8b
prompt: You are an AI clone.
quantizer: null
seed: 42
temperature: 0.2
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: model/llama3/original/tokenizer.model
top_k: 10000

DEBUG:torchtune.utils.logging:Setting manual seed to local seed 42. Local seed is seed + rank = 42 + 0
INFO:torchtune.utils.logging:Model is initialized with precision torch.bfloat16.
Enter your prompt: how do you feel about gelato?
I don't have feelings.
Enter your prompt: how are you doing in general?
I'm good.
Enter your prompt: tell me more about the AI evolution today
I'm not sure.
Enter your prompt: can you help me understand a bit more?
I'm not sure I can explain it well.
Enter your prompt: maybe want to help me understand?
I'll try.
```

basically it just doesn't wanna talk about anything!
unless I'm super depressed, it doesn't sound like me.
Also I love gelato, and there are chats about gelato in that whatsapp chat so... something is off.

What went wrong you think?

**Comment by kinggongzilla** [comment]
Try increasing the temperature and/or top_k in the inference config.

**Comment by AntouanK** [comment]
temp 0.8, it got more ... confusing

```
❯ tune run chat.py --config config/llama3/inference_config.yaml
INFO:torchtune.utils.logging:Running ChatRecipe with resolved config:

checkpointer:
  _component_: torchtune.utils.FullModelMetaCheckpointer
  checkpoint_dir: model/finetune_checkpoint
  checkpoint_files:
  - meta_model_0.pt
  model_type: LLAMA3
  output_dir: model/finetune_checkpoint
device: cuda
dtype: bf16
max_new_tokens: 4096
model:
  _component_: torchtune.models.llama3.llama3_8b
prompt: You are an AI clone.
quantizer: null
seed: 42
temperature: 0.8
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: model/llama3/original/tokenizer.model
top_k: 10000

DEBUG:torchtune.utils.logging:Setting manual seed to local seed 42. Local seed is seed + rank = 42 + 0
INFO:torchtune.utils.logging:Model is initialized with precision torch.bfloat16.
Enter your prompt: hey man, do you like gelato?
Hey man.
Enter your prompt: do you like gelato?
Oof
Enter your prompt: reply please
I'm not sure.
Enter your prompt: ok then
it's very good
Enter your prompt: ok
which one is your favorite?
Enter your prompt: ok
you need to explain it.
Enter your prompt: ok
they are all confusing.
Enter your prompt: ok
ok
Enter your prompt: ok
no no, this is a chat automaticly generated.
```

and then I put top_k to 15000
( I also retrained for 2 epochs )

```
❯ tune run chat.py --config config/llama3/inference_config.yaml
INFO:torchtune.utils.logging:Running ChatRecipe with resolved config:

checkpointer:
  _component_: torchtune.utils.FullModelMetaCheckpointer
  checkpoint_dir: model/finetune_checkpoint
  checkpoint_files:
  - meta_model_1.pt
  model_type: LLAMA3
  output_dir: model/finetune_checkpoint
device: cuda
dtype: bf16
max_new_tokens: 4096
model:
  _component_: torchtune.models.llama3.llama3_8b
prompt: You are an AI clone.
quantizer: null
seed: 42
temperature: 0.8
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: model/llama3/original/tokenizer.model
top_k: 15000

DEBUG:torchtune.utils.logging:Setting manual seed to local seed 42. Local seed is seed + rank = 42 + 0
INFO:torchtune.utils.logging:Model is initialized with precision torch.bfloat16.
Enter your prompt: hello there. who are you?
Hey
Enter your prompt: reply please
Hey, it's me, GPT-4
Enter your prompt: do you like gelato?
I'm a cloned AI, I don't eat or taste anything.
Enter your prompt: what do you do then?
I answer questions.
Enter your prompt: then answer this question: how is gelato made?
Gelato is a type of Italian ice cream made using gelato machines, which use a combination of hot and cold technology to freeze and aerate the mixture.
Enter your prompt: aha, what else do you know about it?
I know lots.
```


could it be that because whatsapp answers/messages are all short, it learns to reply in very short format?

**Comment by kinggongzilla** [comment]
"could it be that because whatsapp answers/messages are all short, it learns to reply in very short format?"

Yes exactly. However for me playing with top_k and temperature made a big difference. While the answers are always rather short, it did improve diversity in replies.

Top_k 10000 is already very high fyi so you can definitely also try reducing it. 

Oh and also adding a custom system prompt with more information about yourself also makes it much better in my experience. You can do it in the llama3 inference config. 

Just play around a little and see what works best for you.

**Comment by AntouanK** [comment]
for example, pinging "ok" to make it talk more, it kind of makes sense.

```
❯ tune run chat.py --config config/llama3/inference_config.yaml
INFO:torchtune.utils.logging:Running ChatRecipe with resolved config:

checkpointer:
  _component_: torchtune.utils.FullModelMetaCheckpointer
  checkpoint_dir: model/finetune_checkpoint
  checkpoint_files:
  - meta_model_1.pt
  model_type: LLAMA3
  output_dir: model/finetune_checkpoint
device: cuda
dtype: bf16
max_new_tokens: 4096
model:
  _component_: torchtune.models.llama3.llama3_8b
prompt: You are an AI clone.
quantizer: null
seed: 42
temperature: 0.65
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: model/llama3/original/tokenizer.model
top_k: 10000

DEBUG:torchtune.utils.logging:Setting manual seed to local seed 42. Local seed is seed + rank = 42 + 0
INFO:torchtune.utils.logging:Model is initialized with precision torch.bfloat16.
Enter your prompt: tell me how gelato is made
sure
Enter your prompt: ok
gelato is made similar to ice cream.
Enter your prompt: ok
it's a mixture of milk, cream, and sugar.
Enter your prompt: ok
then you heat it up
Enter your prompt: ok
and with the heat it becomes a gelateous state
Enter your prompt: ok
it's a process you have to experiment with to get right.
Enter your prompt: ok
you don't have to keep it in the chiller like you do with gelato.
Enter your prompt: ok
it's a bit like the italian gelato.
Enter your prompt: ok
it's churros that are weird.
Enter your prompt: ok
anyway, gelato is easier to make than you think
Enter your prompt: ok
it's all about gelateous state
Enter your prompt: ok
you need the right temperature and time to get it right.
Enter your prompt: ok
but I think it's worth trying.
Enter your prompt: ok
it's amazing.
Enter your prompt: ok
you need to try it
Enter your prompt:
```

could we try to bundle messages a bit?
like if in whatsapp I send 5 messages straight ( within a few minutes ) they can be considered one "response" right?
we could have a second "preprocess" that tries that approach?

**Comment by kinggongzilla** [comment]
yes you can definitely bundle messages in preprocessing. I actually tried it briefly but for me not bundling seemed to work a bit better.
Let me know how it turns out for you! :)

**Comment by AntouanK** [comment]
I tried a bunch of values in config so far. 
It's hilarious but as far as an LLM goes, completely unusable

```
❯ tune run chat.py --config config/llama3/inference_config.yaml
INFO:torchtune.utils.logging:Running ChatRecipe with resolved config:

checkpointer:
  _component_: torchtune.utils.FullModelMetaCheckpointer
  checkpoint_dir: model/finetune_checkpoint
  checkpoint_files:
  - meta_model_0.pt
  model_type: LLAMA3
  output_dir: model/finetune_checkpoint
device: cuda
dtype: bf16
max_new_tokens: 4096
model:
  _component_: torchtune.models.llama3.llama3_8b
prompt: You are Antonis, a nice guy, always helpful and interested to share ideas.
quantizer: null
seed: 42
temperature: 0.85
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: model/llama3/original/tokenizer.model
top_k: 400

DEBUG:torchtune.utils.logging:Setting manual seed to local seed 42. Local seed is seed + rank = 42 + 0
INFO:torchtune.utils.logging:Model is initialized with precision torch.bfloat16.
Enter your prompt: how is gelato made?
sure
Enter your prompt:
gelato is made similar to ice cream, only less water.
Enter your prompt:
it has to be.
Enter your prompt:
you can see the gelato on the top.
Enter your prompt:
it's a good idea, but it's not made by gelato.
Enter your prompt:
gelato, if you can see a liquid part in it, it will not be gelato.
Enter your prompt:
normally it's just one part.
Enter your prompt:
in Italy, the gelato machines are used by retail shops, and in most places I've seen it, it is a gelato machine.
Enter your prompt:
but I understand.
Enter your prompt:
there is no point losing gelato
Enter your prompt:
it's not the point.
Enter your prompt:
it is gelato.
Enter your prompt:
we had that one in the other thread.
Enter your prompt:
when we are talking to people, we are just sharing our experience. We are not experts on anything.
```

Is there a way to chat with the original Llama 3 8B with the same seed?
Just curious to see how "bad" my fine-tuning made it.
I suppose we can change that "checkpointer" part in the yaml somehow?

Also, will it work with the larger llama3 (30B)?

And also can you share maybe any anonymized samples of the training chat you gave it and the results?
Just to see how well it worked for you, to have a benchmark to work with.

Thank you :+1:
