### ISSUE TITLE
bf16 not available and other error

### ISSUE THREAD

**Issue by snailbrainx** [kinggongzilla/ai-clone-whatsapp#9]
Hi and thanks for the project.

I've followed the instructions and i get this error:

bf16 precision was requested but not available on this hardware. Please use fp32 precision instead.

I've set in the yaml to use fp32, and then get this error (any help much appreciated - this will be my first fine tune):

note: I'm using win11, 3090 GPU (have 2 but seems can only use 1, which is fine).

```C:\Users\ac\ai-clone-whatsapp>tune run lora_finetune_single_device --config config/llama3/qlora_train_config.yaml
[2024-05-02 16:40:39,297] torch.distributed.elastic.multiprocessing.redirects: [WARNING] NOTE: Redirects are currently not supported in Windows or MacOs.
INFO:torchtune.utils.logging:Running LoRAFinetuneRecipeSingleDevice with resolved config:

batch_size: 1
checkpointer:
  _component_: torchtune.utils.FullModelMetaCheckpointer
  checkpoint_dir: model/llama3/original
  checkpoint_files:
  - consolidated.00.pth
  model_type: LLAMA3
  output_dir: model/finetune_checkpoint
compile: false
dataset:
  _component_: torchtune.datasets.chat_dataset
  conversation_style: sharegpt
  max_seq_len: 4096
  source: data/preprocessed
  split: train
  train_on_input: false
device: cuda
dtype: fp32
enable_activation_checkpointing: false
epochs: 1
gradient_accumulation_steps: 1
log_every_n_steps: 1
log_peak_memory_stats: false
loss:
  _component_: torch.nn.CrossEntropyLoss
lr_scheduler:
  _component_: torchtune.modules.get_cosine_schedule_with_warmup
  num_warmup_steps: 100
max_steps_per_epoch: null
metric_logger:
  _component_: torchtune.utils.metric_logging.DiskLogger
  log_dir: /tmp/lora_finetune_output
model:
  _component_: torchtune.models.llama3.qlora_llama3_8b
  apply_lora_to_mlp: true
  apply_lora_to_output: true
  lora_alpha: 16
  lora_attn_modules:
  - q_proj
  - k_proj
  - v_proj
  - output_proj
  lora_rank: 8
optimizer:
  _component_: torch.optim.AdamW
  lr: 0.0003
  weight_decay: 0.01
output_dir: /tmp/lora_finetune_output
profiler:
  _component_: torchtune.utils.profiler
  enabled: false
resume_from_checkpoint: false
seed: 42
shuffle: true
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: model/llama3/original/tokenizer.model

DEBUG:torchtune.utils.logging:Setting manual seed to local seed 42. Local seed is seed + rank = 42 + 0
Writing logs to \tmp\lora_finetune_output\log_1714664439.txt
INFO:torchtune.utils.logging:Model is initialized with precision torch.float32.
INFO:torchtune.utils.logging:Memory stats after model init:
        GPU peak memory allocation: 12.35 GB
        GPU peak memory reserved: 13.19 GB
        GPU peak memory active: 12.35 GB
INFO:torchtune.utils.logging:Tokenizer is initialized from file.
INFO:torchtune.utils.logging:Optimizer and loss are initialized.
INFO:torchtune.utils.logging:Loss is initialized.
Resolving data files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 472/472 [00:00<00:00, 12541.01it/s]
Downloading data: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 472/472 [00:00<00:00, 13693.32files/s]
Generating train split: 472 examples [00:02, 167.11 examples/s]
INFO:torchtune.utils.logging:Dataset and Sampler are initialized.
INFO:torchtune.utils.logging:Learning rate scheduler is initialized.
  0%|                                                                                                                                                                        | 0/472 [00:00<?, ?it/s]C:\Users\ac\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torchtune\modules\attention.py:207: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:263.)
  output = nn.functional.scaled_dot_product_attention(
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ac\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts\tune.exe\__main__.py", line 7, in <module>
  File "C:\Users\ac\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torchtune\_cli\tune.py", line 49, in main
    parser.run(args)
  File "C:\Users\ac\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torchtune\_cli\tune.py", line 43, in run
    args.func(args)
  File "C:\Users\ac\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torchtune\_cli\run.py", line 179, in _run_cmd
    self._run_single_device(args)
  File "C:\Users\ac\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torchtune\_cli\run.py", line 93, in _run_single_device
    runpy.run_path(str(args.recipe), run_name="__main__")
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ac\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\recipes\lora_finetune_single_device.py", line 528, in <module>
    sys.exit(recipe_main())
  File "C:\Users\ac\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torchtune\config\_parse.py", line 50, in wrapper
    sys.exit(recipe_main(conf))
  File "C:\Users\ac\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\recipes\lora_finetune_single_device.py", line 523, in recipe_main
    recipe.train()
  File "C:\Users\ac\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\recipes\lora_finetune_single_device.py", line 460, in train
    loss = self._loss_fn(logits, labels)
  File "C:\Users\ac\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\ac\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\ac\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\nn\modules\loss.py", line 1179, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "C:\Users\ac\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\nn\functional.py", line 3059, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
RuntimeError: expected scalar type Long but found Int
  0%|                                                                                                                                                                        | 0/472 [00:01<?, ?it/s]```

**Comment by snailbrainx** [comment]
as an addition - i've tried with cuda 11.8 and 12.7(?)

**Comment by snailbrainx** [comment]
Update:
i added  
`labels = labels.to(torch.long)`

in the single device lora fine tune in torchtune - seems to be doing something now.

i assume setting FP32 and this setting won't cause any issues? 

though i do get this warning:

```INFO:torchtune.utils.logging:Learning rate scheduler is initialized.
  0%|                                                                                                                                                                        | 0/472 [00:00<?, ?it/s]C:\Users\ac\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torchtune\modules\attention.py:207: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:263.)
  output = nn.functional.scaled_dot_product_attention(
1|12|Loss: 4.088680744171143:   3%|███▏                                                                                                                           | 12/472 [04:29<3:52:34, 30.34s/it]```

**Comment by snailbrainx** [comment]
bf16 seems an issue with 3090  pytorch:

https://discuss.pytorch.org/t/fine-tune-llms-using-torchtune/201804

-

update on running fp32 - ran out of vram.

**Comment by kinggongzilla** [comment]
Hm thats odd, I also have a 3090 and it is training just fine with fp16.
You can try to reduce the max_seq_length to lower memory usage and maybe be able to train woth fp32. Currently it is set at 4096, but you can try and set it to 512 or something

**Comment by soccerverse** [comment]
it fnished with 512 with fp32.

when i  try to chat with it though :

`torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 224.00 MiB. GPU 0 has a total capacity of 24.00 GiB of which 0 bytes is free. Of the allocated memory 23.07 GiB is allocated by PyTorch, and 21.22 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)`

tried restarting, tryied setting context to 50.

not a problem with your script - which version of pytorch and cuda are you using?

**Comment by kinggongzilla** [comment]
Hi
I'm using Cuda 12.2 and pytorch 2.2.2

**Comment by yfes** [comment]
hey, got exactly the same problem with the same config, rtx 3090.
did you find a fix for this?

**Comment by snailbrainx** [comment]
> hey, got exactly the same problem with the same config, rtx 3090. did you find a fix for this?

no. but it was all a learning experience for fine tuning in any case. I'm installing it on ubuntu now though.
